name: ppllava-npu
channels:
  - defaults
dependencies:
  - pip
  - python=3.9.16
  - readline=8.2
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - accelerate==0.27.2
    - addict==2.4.0
    - aiofiles==23.2.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.3.0
    - ascendspeed==0.0.1
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==23.2.0
    - blinker==1.7.0
    - braceexpand==0.1.7
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - cli-exit-tools==1.2.6
    - click==8.1.7
    - cloudpickle==3.0.0
    - contourpy==1.2.1
    - cos-python-sdk-v5==1.9.28
    - crcmod==1.7
    - cycler==0.12.1
    - datasets==2.18.0
    - decorator==5.1.1
    - deepspeed==0.14.0
    - dill==0.3.8
    - dulwich==0.21.7
    - einops==0.7.0
    - exceptiongroup==1.2.0
    - expecttest==0.2.1
    - fastapi==0.110.1
    - ffmpy==0.3.2
    - filelock==3.13.4
    - flask==3.0.3
    - flask-cors==4.0.0
    - fonttools==4.51.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - ftfy==6.2.0
    - fuzzywuzzy==0.18.0
    - gradio==3.50.2
    - gradio-client==0.6.1
    - grpcio==1.62.1
    - gunicorn==22.0.0
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.26.1
    - hydra-core==1.3.2
    - idna==3.7
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - iniconfig==2.0.0
    - itsdangerous==2.2.0
    - jieba==0.42.1
    - jinja2==3.1.3
    - joblib==1.4.0
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - latex2mathml==3.77.0
    - lib-detect-testenv==2.0.8
    - markdown==3.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - marshmallow==3.21.1
    - matplotlib==3.8.4
    - mdtex2html==1.3.0
    - mdurl==0.1.2
    - mmcv==2.2.0
    - mmengine==0.10.5
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nltk==3.8.1
    - numpy==1.26.4
    - omegaconf==2.3.0
    - opencv-python-headless==4.8.1.78
    - orjson==3.10.1
    - packaging==24.0
    - pandas==1.2.5
    - pillow==10.3.0
    - pluggy==1.4.0
    - prettytable==3.10.0
    - protobuf==3.20.0
    - psutil==5.9.8
    - py-cpuinfo==9.0.0
    - pyarrow==12.0.1
    - pyarrow-hotfix==0.6
    - pybind11==2.12.0
    - pycryptodome==3.20.0
    - pydantic==1.10.15
    - pydantic-core==2.18.1
    - pydub==0.25.1
    - pygments==2.17.2
    - pynvml==11.5.0
    - pyparsing==3.1.2
    - pyrootutils==1.0.4
    - pytest==8.1.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-multipart==0.0.9
    - pytz==2024.1
    - pyyaml==6.0.1
    - referencing==0.34.0
    - regex==2024.4.16
    - requests==2.31.0
    - rich==13.7.1
    - rouge-chinese==1.0.3
    - rpds-py==0.18.0
    - safetensors==0.4.3
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - setuptools==69.0.3
    - six==1.16.0
    - sniffio==1.3.1
    - starlette==0.37.2
    - sympy==1.12
    - synr==0.5.0
    - tbe==0.0.4
    - termcolor==2.5.0
    - threadpoolctl==3.4.0
    - tiktoken==0.5.2
    - tokenizers==0.13.3
    - tomli==2.0.1
    - toolz==0.12.1
    - torch==2.1.0+cpu
    - torchaudio==2.1.0
    - torchdata==0.6.1
    - torchvision==0.16.0
    - tornado==6.4
    - tqdm==4.66.2
    - transformers-stream-generator==0.0.5
    - treelib==1.7.0
    - typing-extensions==4.11.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - urwid==2.6.10
    - uvicorn==0.29.0
    - venus-api-all==1.3.21
    - venus-api-base==1.3.21
    - venus-boot==1.3.21
    - venus-flow==1.3.21
    - venus-flow-operator==1.3.21
    - venus-ml==1.3.21
    - venus-sdk==1.3.21
    - venus-tools==1.3.21
    - wcwidth==0.2.13
    - websockets==11.0.3
    - werkzeug==3.0.2
    - wrapt==1.16.0
    - wrapt-timeout-decorator==1.5.1
    - xlsxwriter==3.2.0
    - xmltodict==0.13.0
    - xxhash==3.4.1
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.18.1


